# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
